apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: golden-gopher-go
  janus-idp.io/tekton: golden-gopher-go
  backstage.io/kubernetes-id: golden-gopher-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: golden-gopher-go
resources: 
- deployment.yaml
- route.yaml
- service.yaml
